const fs = require('fs');
let content = fs.readFileSync('src/translations.ts', 'utf8');

const replacements = [
  { match: /cash: "Cash at Home & Bank",/, replace: 'cashAtHome: "Cash at Home",\n    cashInBank: "Cash in Bank",\n    helpSectionTitle: "Help & Support",\n    helpSectionDesc: "If you find any mistakes or need help, please contact us on WhatsApp.",\n    contactWhatsApp: "Contact on WhatsApp",' },
  { match: /cash: "घर और बैंक में नकद",/, replace: 'cashAtHome: "घर में नकद",\n    cashInBank: "बैंक में नकद",\n    helpSectionTitle: "सहायता और समर्थन",\n    helpSectionDesc: "यदि आपको कोई गलती मिलती है या सहायता की आवश्यकता है, तो कृपया हमें व्हाट्सएप पर संपर्क करें।",\n    contactWhatsApp: "व्हाट्सएप पर संपर्क करें",' },
  { match: /cash: "گھر اور بینک میں نقد رقم",/, replace: 'cashAtHome: "گھر میں نقد",\n    cashInBank: "بینک میں نقد",\n    helpSectionTitle: "مدد اور تعاون",\n    helpSectionDesc: "اگر آپ کو کوئی غلطی نظر آئے یا مدد کی ضرورت ہو تو براہ کرم ہم سے واٹس ایپ پر رابطہ کریں۔",\n    contactWhatsApp: "واٹس ایپ پر رابطہ کریں",' },
  { match: /cash: "النقد في المنزل والبنك",/, replace: 'cashAtHome: "النقد في المنزل",\n    cashInBank: "النقد في البنك",\n    helpSectionTitle: "المساعدة والدعم",\n    helpSectionDesc: "إذا وجدت أي أخطاء أو كنت بحاجة إلى مساعدة، يرجى الاتصال بنا على واتساب.",\n    contactWhatsApp: "تواصل على واتساب",' },
  { match: /cash: "নগদ অর্থ \\(ঘরে ও ব্যাংকে\\)",/, replace: 'cashAtHome: "ঘরে নগদ অর্থ",\n    cashInBank: "ব্যাংকে নগদ অর্থ",\n    helpSectionTitle: "সাহায্য ও সমর্থন",\n    helpSectionDesc: "যদি আপনি কোনো ভুল পান বা সাহায্যের প্রয়োজন হয়, অনুগ্রহ করে হোয়াটসঅ্যাপে আমাদের সাথে যোগাযোগ করুন।",\n    contactWhatsApp: "হোয়াটসঅ্যাপে যোগাযোগ করুন",' },
  { match: /cash: "Uang Tunai di Rumah & Bank",/, replace: 'cashAtHome: "Uang Tunai di Rumah",\n    cashInBank: "Uang Tunai di Bank",\n    helpSectionTitle: "Bantuan & Dukungan",\n    helpSectionDesc: "Jika Anda menemukan kesalahan atau butuh bantuan, silakan hubungi kami di WhatsApp.",\n    contactWhatsApp: "Hubungi di WhatsApp",' },
  { match: /cash: "Evdeki ve Bankadaki Nakit",/, replace: 'cashAtHome: "Evdeki Nakit",\n    cashInBank: "Bankadaki Nakit",\n    helpSectionTitle: "Yardım ve Destek",\n    helpSectionDesc: "Herhangi bir hata bulursanız veya yardıma ihtiyacınız olursa, lütfen WhatsApp üzerinden bizimle iletişime geçin.",\n    contactWhatsApp: "WhatsApp\'tan İletişime Geçin",' },
  { match: /cash: "Espèces à la Maison et en Banque",/, replace: 'cashAtHome: "Espèces à la Maison",\n    cashInBank: "Espèces en Banque",\n    helpSectionTitle: "Aide et Support",\n    helpSectionDesc: "Si vous trouvez des erreurs ou avez besoin d\'aide, veuillez nous contacter sur WhatsApp.",\n    contactWhatsApp: "Contacter sur WhatsApp",' },
  { match: /cash: "Efectivo en Casa y Banco",/, replace: 'cashAtHome: "Efectivo en Casa",\n    cashInBank: "Efectivo en Banco",\n    helpSectionTitle: "Ayuda y Soporte",\n    helpSectionDesc: "Si encuentra algún error o necesita ayuda, contáctenos en WhatsApp.",\n    contactWhatsApp: "Contactar en WhatsApp",' },
  { match: /cash: "घरी आणि बँकेत रोख",/, replace: 'cashAtHome: "घरी रोख",\n    cashInBank: "बँकेत रोख",\n    helpSectionTitle: "मदत आणि समर्थन",\n    helpSectionDesc: "तुम्हाला काही चुका आढळल्यास किंवा मदतीची आवश्यकता असल्यास, कृपया आमच्याशी व्हॉट्सॲपवर संपर्क साधा.",\n    contactWhatsApp: "व्हॉट्सॲपवर संपर्क साधा",' },
  { match: /cash: "ఇంట్లో & బ్యాంకులో నగదు",/, replace: 'cashAtHome: "ఇంట్లో నగదు",\n    cashInBank: "బ్యాంకులో నగదు",\n    helpSectionTitle: "సహాయం & మద్దతు",\n    helpSectionDesc: "మీరు ఏవైనా తప్పులు కనుగొంటే లేదా సహాయం కావాలంటే, దయచేసి వాట్సాప్‌లో మమ్మల్ని సంప్రదించండి.",\n    contactWhatsApp: "వాట్సాప్‌లో సంప్రదించండి",' },
  { match: /cash: "வீடு & வங்கியில் பணம்",/, replace: 'cashAtHome: "வீட்டில் பணம்",\n    cashInBank: "வங்கியில் பணம்",\n    helpSectionTitle: "உதவி மற்றும் ஆதரவு",\n    helpSectionDesc: "ஏதேனும் தவறுகளைக் கண்டால் அல்லது உதவி தேவைப்பட்டால், வாட்ஸ்அப்பில் எங்களைத் தொடர்புகொள்ளவும்.",\n    contactWhatsApp: "வாட்ஸ்அப்பில் தொடர்புகொள்ளவும்",' },
  { match: /cash: "ઘરે અને બેંકમાં રોકડ",/, replace: 'cashAtHome: "ઘરે રોકડ",\n    cashInBank: "બેંકમાં રોકડ",\n    helpSectionTitle: "મદદ અને આધાર",\n    helpSectionDesc: "જો તમને કોઈ ભૂલો જણાય અથવા મદદની જરૂર હોય, તો કૃપા કરીને WhatsApp પર અમારો સંપર્ક કરો.",\n    contactWhatsApp: "WhatsApp પર સંપર્ક કરો",' },
  { match: /cash: "ಮನೆಯಲ್ಲಿ ಮತ್ತು ಬ್ಯಾಂಕಿನಲ್ಲಿರುವ ನಗದು",/, replace: 'cashAtHome: "ಮನೆಯಲ್ಲಿರುವ ನಗದು",\n    cashInBank: "ಬ್ಯಾಂಕಿನಲ್ಲಿರುವ ನಗದು",\n    helpSectionTitle: "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",\n    helpSectionDesc: "ನೀವು ಯಾವುದೇ ತಪ್ಪುಗಳನ್ನು ಕಂಡುಕೊಂಡರೆ ಅಥವಾ ಸಹಾಯದ ಅಗತ್ಯವಿದ್ದರೆ, ದಯವಿಟ್ಟು WhatsApp ನಲ್ಲಿ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.",\n    contactWhatsApp: "WhatsApp ನಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ",' },
  { match: /cash: "വീട്ടിലെയും ബാങ്കിലെയും പണം",/, replace: 'cashAtHome: "വീട്ടിലെ പണം",\n    cashInBank: "ബാങ്കിലെ പണം",\n    helpSectionTitle: "സഹായവും പിന്തുണയും",\n    helpSectionDesc: "നിങ്ങൾക്ക് എന്തെങ്കിലും തെറ്റുകൾ കണ്ടെത്തുകയോ സഹായം ആവശ്യമുണ്ടെങ്കിലോ, ദയവായി WhatsApp-ൽ ഞങ്ങളെ ബന്ധപ്പെടുക.",\n    contactWhatsApp: "WhatsApp-ൽ ബന്ധപ്പെടുക",' },
  { match: /cashBank: "ਨਕਦ ਅਤੇ ਬੈਂਕ ਬੈਲੇਂਸ",/, replace: 'cashAtHome: "ਘਰ ਵਿੱਚ ਨਕਦ",\n    cashInBank: "ਬੈਂਕ ਵਿੱਚ ਨਕਦ",\n    helpSectionTitle: "ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ",\n    helpSectionDesc: "ਜੇਕਰ ਤੁਹਾਨੂੰ ਕੋਈ ਗਲਤੀ ਮਿਲਦੀ ਹੈ ਜਾਂ ਮਦਦ ਦੀ ਲੋੜ ਹੈ, ਤਾਂ ਕਿਰਪਾ ਕਰਕੇ WhatsApp \'ਤੇ ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",\n    contactWhatsApp: "WhatsApp \'ਤੇ ਸੰਪਰਕ ਕਰੋ",' },
  { match: /cashBank: "ନଗଦ ଏବଂ ବ୍ୟାଙ୍କ ବାଲାନ୍ସ",/, replace: 'cashAtHome: "ଘରେ ନଗଦ",\n    cashInBank: "ବ୍ୟାଙ୍କରେ ନଗଦ",\n    helpSectionTitle: "ସାହାଯ୍ୟ ଏବଂ ସମର୍ଥନ",\n    helpSectionDesc: "ଯଦି ଆପଣ କୌଣସି ଭୁଲ ଦେଖନ୍ତି କିମ୍ବା ସାହାଯ୍ୟ ଦରକାର କରନ୍ତି, ଦୟାକରି WhatsApp ରେ ଆମ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।",\n    contactWhatsApp: "WhatsApp ରେ ଯୋଗାଯୋଗ କରନ୍ତୁ",' },
  { match: /cashBank: "নগদ আৰু বেংক বেলেঞ্চ",/, replace: 'cashAtHome: "ঘৰত নগদ",\n    cashInBank: "বেংকত নগদ",\n    helpSectionTitle: "সহায় আৰু সমৰ্থন",\n    helpSectionDesc: "যদি আপুনি কোনো ভুল পায় বা সহায়ৰ প্ৰয়োজন হয়, অনুগ্ৰহ কৰি WhatsApp ত আমাৰ সৈতে যোগাযোগ কৰক।",\n    contactWhatsApp: "WhatsApp ত যোগাযোগ কৰক",' }
];

replacements.forEach(r => {
  content = content.replace(r.match, r.replace);
});

fs.writeFileSync('src/translations.ts', content);
